/**
 * Cover-art registry. Soft hand-painted watercolour illustrations (Recraft 4.1,
 * locked to the brand eucalyptus/sage palette with soft peach accents) - one
 * cohesive light, airy fine-art set, standing in for the licensed artwork Glowco
 * supplies in production (V1_SCOPE: Glowco provides all media/brand assets). §7.
 */
export const covers = {
  slowTide: require('../../assets/covers/slow-tide.webp'),
  rainfall: require('../../assets/covers/rainfall.webp'),
  boxBreathing: require('../../assets/covers/box-breathing.webp'),
  deepRest: require('../../assets/covers/deep-rest.webp'),
  lettingGo: require('../../assets/covers/letting-go.webp'),
  forestStream: require('../../assets/covers/forest-stream.webp'),
  penguinVoyage: require('../../assets/covers/penguin-voyage.webp'),
  spaMusic: require('../../assets/covers/spa-music.webp'),
  gymnopedie: require('../../assets/covers/gymnopedie.webp'),
  shoreline: require('../../assets/covers/shoreline.webp'),
  fireside: require('../../assets/covers/fireside.webp'),
  dawnWoods: require('../../assets/covers/dawn-woods.webp'),
  brownNoise: require('../../assets/covers/brown-noise.webp'),
  pinkNoise: require('../../assets/covers/pink-noise.webp'),
  whiteNoise: require('../../assets/covers/white-noise.webp'),

  // Per-track covers so siblings no longer share one painting (2026-08 polish).
  deskFan: require('../../assets/covers/desk-fan.webp'),
  acHum: require('../../assets/covers/ac-hum.webp'),
  tumbleDryer: require('../../assets/covers/tumble-dryer.webp'),
  winterWind: require('../../assets/covers/winter-wind.webp'),
  shush: require('../../assets/covers/shush.webp'),
  greenNoise: require('../../assets/covers/green-noise.webp'),
  rainForest: require('../../assets/covers/rain-forest.webp'),
  softWind: require('../../assets/covers/soft-wind.webp'),
  leafWind: require('../../assets/covers/leaf-wind.webp'),
  forestDusk: require('../../assets/covers/forest-dusk.webp'),
  rainWindow: require('../../assets/covers/rain-window.webp'),
  rainTent: require('../../assets/covers/rain-tent.webp'),
  rainDistant: require('../../assets/covers/rain-distant.webp'),
  rainHeavy: require('../../assets/covers/rain-heavy.webp'),
  rainPiano: require('../../assets/covers/rain-piano.webp'),
  rainOcean: require('../../assets/covers/rain-ocean.webp'),
  beachFire: require('../../assets/covers/beach-fire.webp'),
  seaDunes: require('../../assets/covers/sea-dunes.webp'),
  shoreMorning: require('../../assets/covers/shore-morning.webp'),
  stormRolling: require('../../assets/covers/storm-rolling.webp'),
  rainFire: require('../../assets/covers/rain-fire.webp'),
  embers: require('../../assets/covers/embers.webp'),
  forestCampfire: require('../../assets/covers/forest-campfire.webp'),
  firesideHush: require('../../assets/covers/fireside-hush.webp'),
  theCabin: require('../../assets/covers/the-cabin.webp'),
  softFan: require('../../assets/covers/soft-fan.webp'),
  ceilingFan: require('../../assets/covers/ceiling-fan.webp'),
  nightTrain: require('../../assets/covers/night-train.webp'),
  nightDrive: require('../../assets/covers/night-drive.webp'),
  mountainWind: require('../../assets/covers/mountain-wind.webp'),
  birdsFar: require('../../assets/covers/birds-far.webp'),
  pianoBirds: require('../../assets/covers/piano-birds.webp'),
  airplaneCabin: require('../../assets/covers/airplane-cabin.webp'),
  deepSwell: require('../../assets/covers/deep-swell.webp'),
  pianoSea: require('../../assets/covers/piano-sea.webp'),
  pianoFire: require('../../assets/covers/piano-fire.webp'),
  gymnopedieRain: require('../../assets/covers/gymnopedie-rain.webp'),
} as const;

export type CoverKey = keyof typeof covers;
